In [1]:
import pandas as pd
import numpy as np

ModuleNotFoundError: No module named 'pandas'

In [2]:
! pip install numpy pandas

Collecting numpy
  Downloading numpy-1.26.2-cp310-cp310-win_amd64.whl.metadata (61 kB)
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.2 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.2 kB 162.5 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.2 kB 163.8 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 217.9 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 217.9 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 217.9 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 217.9 kB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 141.6 kB/s eta 0:00:00
Collecting pandas
  Downloading pandas-2.1.4-cp310-cp310-win_amd64.whl.metadata (18 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\405\anaconda3\envs\lambda3_10\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\405\anaconda3\envs\lambda3_10\lib\site-packages (from pandas) (2023.3.post1)
Collecting tzdata>=2022.1 (from pandas)
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     ---------------------------------------- 0.0/341.8 kB ? eta -:--:--
     --------- ----------------------------- 81.9/341.8 kB 2.3 MB/s eta 0:00:01
     ------------------------------ ------- 276.5/341.8 kB 2.8 MB/s eta 0:00:01
     -------------------------------------  337.9/341.8 kB 3.0 MB/s eta 0:00:01
     -------------------------------------- 341.8/341.8 kB 2.4 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in c:\users\405\anaconda3\envs\lambda3_10\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading numpy-1.26.2-cp310-cp310-win_amd64.whl (15.8 MB)
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
    --------------------------------------- 0.2/15.8 MB 6.9 MB/s eta 0:00:03
    --------------------------------------- 0.3/15.8 MB 4.2 MB/s eta 0:00:04
   - -------------------------------------- 0.5/15.8 MB 3.5 MB/s eta 0:00:05
   - -------------------------------------- 0.6/15.8 MB 3.6 MB/s eta 0:00:05
   - -------------------------------------- 0.7/15.8 MB 3.1 MB/s eta 0:00:05
   - -------------------------------------- 0.8/15.8 MB 2.8 MB/s eta 0:00:06
   -- ------------------------------------- 0.8/15.8 MB 2.7 MB/s eta 0:00:06
   -- ------------------------------------- 0.9/15.8 MB 2.5 MB/s eta 0:00:06
   -- ------------------------------------- 0.9/15.8 MB 2.3 MB/s eta 0:00:07
   -- ------------------------------------- 1.0/15.8 MB 2.2 MB/s eta 0:00:07
   -- ------------------------------------- 1.0/15.8 MB 2.1 MB/s eta 0:00:08
   -- ------------------------------------- 1.1/15.8 MB 2.0 MB/s eta 0:00:08
   -- ------------------------------------- 1.1/15.8 MB 2.0 MB/s eta 0:00:08
   --- ------------------------------------ 1.2/15.8 MB 1.9 MB/s eta 0:00:08
   --- ------------------------------------ 1.3/15.8 MB 1.8 MB/s eta 0:00:08
   --- ------------------------------------ 1.3/15.8 MB 1.8 MB/s eta 0:00:09
   --- ------------------------------------ 1.4/15.8 MB 1.8 MB/s eta 0:00:09
   --- ------------------------------------ 1.4/15.8 MB 1.7 MB/s eta 0:00:09
   --- ------------------------------------ 1.5/15.8 MB 1.7 MB/s eta 0:00:09
   --- ------------------------------------ 1.5/15.8 MB 1.7 MB/s eta 0:00:09
   ---- ----------------------------------- 1.6/15.8 MB 1.7 MB/s eta 0:00:09
   ---- ----------------------------------- 1.6/15.8 MB 1.6 MB/s eta 0:00:09
   ---- ----------------------------------- 1.7/15.8 MB 1.6 MB/s eta 0:00:09
   ---- ----------------------------------- 1.7/15.8 MB 1.6 MB/s eta 0:00:09
   ---- ----------------------------------- 1.8/15.8 MB 1.5 MB/s eta 0:00:10
   ---- ----------------------------------- 1.8/15.8 MB 1.5 MB/s eta 0:00:10
   ---- ----------------------------------- 1.9/15.8 MB 1.5 MB/s eta 0:00:10
   ---- ----------------------------------- 1.9/15.8 MB 1.5 MB/s eta 0:00:10
   ---- ----------------------------------- 2.0/15.8 MB 1.5 MB/s eta 0:00:10
   ----- ---------------------------------- 2.0/15.8 MB 1.5 MB/s eta 0:00:10
   ----- ---------------------------------- 2.1/15.8 MB 1.4 MB/s eta 0:00:10
   ----- ---------------------------------- 2.1/15.8 MB 1.4 MB/s eta 0:00:10
   ----- ---------------------------------- 2.2/15.8 MB 1.4 MB/s eta 0:00:10
   ----- ---------------------------------- 2.2/15.8 MB 1.4 MB/s eta 0:00:10
   ----- ---------------------------------- 2.3/15.8 MB 1.4 MB/s eta 0:00:10
   ------ --------------------------------- 2.4/15.8 MB 1.4 MB/s eta 0:00:10
   ------ --------------------------------- 2.4/15.8 MB 1.4 MB/s eta 0:00:10
   ------ --------------------------------- 2.5/15.8 MB 1.4 MB/s eta 0:00:10
   ------ --------------------------------- 2.5/15.8 MB 1.4 MB/s eta 0:00:10
   ------ --------------------------------- 2.6/15.8 MB 1.4 MB/s eta 0:00:10
   ------ --------------------------------- 2.7/15.8 MB 1.4 MB/s eta 0:00:10
   ------ --------------------------------- 2.7/15.8 MB 1.4 MB/s eta 0:00:10
   ------ --------------------------------- 2.7/15.8 MB 1.4 MB/s eta 0:00:10
   ------- -------------------------------- 2.8/15.8 MB 1.4 MB/s eta 0:00:10
   ------- -------------------------------- 2.8/15.8 MB 1.4 MB/s eta 0:00:10
   ------- -------------------------------- 2.9/15.8 MB 1.3 MB/s eta 0:00:10
   ------- -------------------------------- 2.9/15.8 MB 1.3 MB/s eta 0:00:10
   ------- -------------------------------- 2.9/15.8 MB 1.3 MB/s eta 0:00:10
   ------- -------------------------------- 2.9/15.8 MB 1.3 MB/s eta 0:00:10
   ------- -------------------------------- 3.0/15.8 MB 1.3 MB/s eta 0:00:10
   ------- -------------------------------- 3.0/15.8 MB 1.3 MB/s eta 0:00:10
   ------- -------------------------------- 3.1/15.8 MB 1.3 MB/s eta 0:00:10
   ------- -------------------------------- 3.1/15.8 MB 1.3 MB/s eta 0:00:11
   ------- -------------------------------- 3.1/15.8 MB 1.3 MB/s eta 0:00:11
   ------- -------------------------------- 3.1/15.8 MB 1.3 MB/s eta 0:00:11
   -------- ------------------------------- 3.2/15.8 MB 1.2 MB/s eta 0:00:11
   -------- ------------------------------- 3.2/15.8 MB 1.2 MB/s eta 0:00:11
   -------- ------------------------------- 3.2/15.8 MB 1.2 MB/s eta 0:00:11
   -------- ------------------------------- 3.3/15.8 MB 1.2 MB/s eta 0:00:11
   -------- ------------------------------- 3.3/15.8 MB 1.2 MB/s eta 0:00:11
   -------- ------------------------------- 3.4/15.8 MB 1.2 MB/s eta 0:00:11
   -------- ------------------------------- 3.4/15.8 MB 1.2 MB/s eta 0:00:11
   -------- ------------------------------- 3.5/15.8 MB 1.2 MB/s eta 0:00:11
   -------- ------------------------------- 3.5/15.8 MB 1.2 MB/s eta 0:00:11
   -------- ------------------------------- 3.6/15.8 MB 1.2 MB/s eta 0:00:11
   --------- ------------------------------ 3.6/15.8 MB 1.2 MB/s eta 0:00:11
   --------- ------------------------------ 3.6/15.8 MB 1.2 MB/s eta 0:00:11
   --------- ------------------------------ 3.7/15.8 MB 1.2 MB/s eta 0:00:11
   --------- ------------------------------ 3.7/15.8 MB 1.2 MB/s eta 0:00:11
   --------- ------------------------------ 3.7/15.8 MB 1.2 MB/s eta 0:00:11
   --------- ------------------------------ 3.8/15.8 MB 1.2 MB/s eta 0:00:11
   --------- ------------------------------ 3.8/15.8 MB 1.1 MB/s eta 0:00:11
   --------- ------------------------------ 3.8/15.8 MB 1.1 MB/s eta 0:00:11
   --------- ------------------------------ 3.8/15.8 MB 1.1 MB/s eta 0:00:11
   --------- ------------------------------ 3.8/15.8 MB 1.1 MB/s eta 0:00:11
   --------- ------------------------------ 3.9/15.8 MB 1.1 MB/s eta 0:00:11
   --------- ------------------------------ 3.9/15.8 MB 1.1 MB/s eta 0:00:11
   --------- ------------------------------ 3.9/15.8 MB 1.1 MB/s eta 0:00:11
   ---------- ----------------------------- 4.0/15.8 MB 1.1 MB/s eta 0:00:11
   ---------- ----------------------------- 4.0/15.8 MB 1.1 MB/s eta 0:00:11
   ---------- ----------------------------- 4.0/15.8 MB 1.1 MB/s eta 0:00:11
   ---------- ----------------------------- 4.1/15.8 MB 1.1 MB/s eta 0:00:11
   ---------- ----------------------------- 4.1/15.8 MB 1.1 MB/s eta 0:00:11
   ---------- ----------------------------- 4.1/15.8 MB 1.1 MB/s eta 0:00:11
   ---------- ----------------------------- 4.1/15.8 MB 1.1 MB/s eta 0:00:12
   ---------- ----------------------------- 4.1/15.8 MB 1.0 MB/s eta 0:00:12
   ---------- ----------------------------- 4.1/15.8 MB 1.0 MB/s eta 0:00:12
   ---------- ----------------------------- 4.2/15.8 MB 1.0 MB/s eta 0:00:12
   ---------- ----------------------------- 4.2/15.8 MB 1.0 MB/s eta 0:00:12
   ---------- ----------------------------- 4.2/15.8 MB 1.0 MB/s eta 0:00:12
   ---------- ----------------------------- 4.2/15.8 MB 1.0 MB/s eta 0:00:12
   ---------- ----------------------------- 4.2/15.8 MB 1.0 MB/s eta 0:00:12
   ---------- ----------------------------- 4.3/15.8 MB 1.0 MB/s eta 0:00:12
   ---------- ----------------------------- 4.3/15.8 MB 1.0 MB/s eta 0:00:12
   ---------- ----------------------------- 4.3/15.8 MB 996.1 kB/s eta 0:00:12
   ----------- ---------------------------- 4.4/15.8 MB 989.0 kB/s eta 0:00:12
   ----------- ---------------------------- 4.4/15.8 MB 986.5 kB/s eta 0:00:12
   ----------- ---------------------------- 4.4/15.8 MB 982.0 kB/s eta 0:00:12
   ----------- ---------------------------- 4.5/15.8 MB 984.3 kB/s eta 0:00:12
   ----------- ---------------------------- 4.5/15.8 MB 980.9 kB/s eta 0:00:12
   ----------- ---------------------------- 4.5/15.8 MB 978.6 kB/s eta 0:00:12
   ----------- ---------------------------- 4.6/15.8 MB 977.5 kB/s eta 0:00:12
   ----------- ---------------------------- 4.6/15.8 MB 979.8 kB/s eta 0:00:12
   ----------- ---------------------------- 4.6/15.8 MB 971.3 kB/s eta 0:00:12
   ----------- ---------------------------- 4.7/15.8 MB 970.4 kB/s eta 0:00:12
   ----------- ---------------------------- 4.7/15.8 MB 971.5 kB/s eta 0:00:12
   ------------ --------------------------- 4.8/15.8 MB 971.6 kB/s eta 0:00:12
   ------------ --------------------------- 4.8/15.8 MB 965.5 kB/s eta 0:00:12
   ------------ --------------------------- 4.8/15.8 MB 965.6 kB/s eta 0:00:12
   ------------ --------------------------- 4.9/15.8 MB 966.8 kB/s eta 0:00:12
   ------------ --------------------------- 4.9/15.8 MB 967.9 kB/s eta 0:00:12
   ------------ --------------------------- 5.0/15.8 MB 969.1 kB/s eta 0:00:12
   ------------ --------------------------- 5.0/15.8 MB 969.2 kB/s eta 0:00:12
   ------------ --------------------------- 5.1/15.8 MB 969.4 kB/s eta 0:00:12
   ------------ --------------------------- 5.1/15.8 MB 970.5 kB/s eta 0:00:11
   ------------- -------------------------- 5.2/15.8 MB 975.4 kB/s eta 0:00:11
   ------------- -------------------------- 5.3/15.8 MB 982.2 kB/s eta 0:00:11
   ------------- -------------------------- 5.3/15.8 MB 987.9 kB/s eta 0:00:11
   ------------- -------------------------- 5.4/15.8 MB 994.4 kB/s eta 0:00:11
   ------------- -------------------------- 5.4/15.8 MB 989.6 kB/s eta 0:00:11
   ------------- -------------------------- 5.5/15.8 MB 985.8 kB/s eta 0:00:11
   -------------- ------------------------- 5.5/15.8 MB 989.5 kB/s eta 0:00:11
   -------------- ------------------------- 5.6/15.8 MB 990.5 kB/s eta 0:00:11
   -------------- ------------------------- 5.6/15.8 MB 985.7 kB/s eta 0:00:11
   -------------- ------------------------- 5.6/15.8 MB 985.0 kB/s eta 0:00:11
   -------------- ------------------------- 5.7/15.8 MB 985.8 kB/s eta 0:00:11
   -------------- ------------------------- 5.8/15.8 MB 988.4 kB/s eta 0:00:11
   -------------- ------------------------- 5.8/15.8 MB 991.0 kB/s eta 0:00:11
   -------------- ------------------------- 5.8/15.8 MB 981.3 kB/s eta 0:00:11
   -------------- ------------------------- 5.8/15.8 MB 981.3 kB/s eta 0:00:11
   -------------- ------------------------- 5.8/15.8 MB 973.7 kB/s eta 0:00:11
   -------------- ------------------------- 5.9/15.8 MB 972.1 kB/s eta 0:00:11
   -------------- ------------------------- 5.9/15.8 MB 969.7 kB/s eta 0:00:11
   --------------- ------------------------ 5.9/15.8 MB 970.5 kB/s eta 0:00:11
   --------------- ------------------------ 6.0/15.8 MB 965.6 kB/s eta 0:00:11
   --------------- ------------------------ 6.0/15.8 MB 957.6 kB/s eta 0:00:11
   --------------- ------------------------ 6.0/15.8 MB 957.6 kB/s eta 0:00:11
   --------------- ------------------------ 6.0/15.8 MB 951.3 kB/s eta 0:00:11
   --------------- ------------------------ 6.0/15.8 MB 951.3 kB/s eta 0:00:11
   --------------- ------------------------ 6.0/15.8 MB 938.3 kB/s eta 0:00:11
   --------------- ------------------------ 6.0/15.8 MB 938.3 kB/s eta 0:00:11
   --------------- ------------------------ 6.0/15.8 MB 928.6 kB/s eta 0:00:11
   --------------- ------------------------ 6.0/15.8 MB 928.6 kB/s eta 0:00:11
   --------------- ------------------------ 6.0/15.8 MB 928.6 kB/s eta 0:00:11
   --------------- ------------------------ 6.0/15.8 MB 928.6 kB/s eta 0:00:11
   --------------- ------------------------ 6.0/15.8 MB 928.6 kB/s eta 0:00:11
   --------------- ------------------------ 6.0/15.8 MB 928.6 kB/s eta 0:00:11
   --------------- ------------------------ 6.1/15.8 MB 893.1 kB/s eta 0:00:11
   --------------- ------------------------ 6.1/15.8 MB 893.1 kB/s eta 0:00:11
   --------------- ------------------------ 6.1/15.8 MB 893.1 kB/s eta 0:00:11
   --------------- ------------------------ 6.1/15.8 MB 880.3 kB/s eta 0:00:12
   --------------- ------------------------ 6.1/15.8 MB 873.3 kB/s eta 0:00:12
   --------------- ------------------------ 6.1/15.8 MB 873.3 kB/s eta 0:00:12
   --------------- ------------------------ 6.1/15.8 MB 873.3 kB/s eta 0:00:12
   --------------- ------------------------ 6.1/15.8 MB 860.4 kB/s eta 0:00:12
   --------------- ------------------------ 6.1/15.8 MB 859.4 kB/s eta 0:00:12
   --------------- ------------------------ 6.2/15.8 MB 858.1 kB/s eta 0:00:12
   --------------- ------------------------ 6.2/15.8 MB 855.0 kB/s eta 0:00:12
   --------------- ------------------------ 6.2/15.8 MB 855.6 kB/s eta 0:00:12
   --------------- ------------------------ 6.3/15.8 MB 854.3 kB/s eta 0:00:12
   --------------- ------------------------ 6.3/15.8 MB 853.4 kB/s eta 0:00:12
   --------------- ------------------------ 6.3/15.8 MB 850.3 kB/s eta 0:00:12
   ---------------- ----------------------- 6.3/15.8 MB 848.8 kB/s eta 0:00:12
   ---------------- ----------------------- 6.4/15.8 MB 850.6 kB/s eta 0:00:12
   ---------------- ----------------------- 6.4/15.8 MB 849.4 kB/s eta 0:00:12
   ---------------- ----------------------- 6.5/15.8 MB 851.0 kB/s eta 0:00:11
   ---------------- ----------------------- 6.5/15.8 MB 853.8 kB/s eta 0:00:11
   ---------------- ----------------------- 6.6/15.8 MB 856.9 kB/s eta 0:00:11
   ---------------- ----------------------- 6.6/15.8 MB 856.6 kB/s eta 0:00:11
   ---------------- ----------------------- 6.7/15.8 MB 859.8 kB/s eta 0:00:11
   ----------------- ---------------------- 6.7/15.8 MB 859.9 kB/s eta 0:00:11
   ----------------- ---------------------- 6.8/15.8 MB 860.8 kB/s eta 0:00:11
   ----------------- ---------------------- 6.8/15.8 MB 861.3 kB/s eta 0:00:11
   ----------------- ---------------------- 6.9/15.8 MB 863.1 kB/s eta 0:00:11
   ----------------- ---------------------- 6.9/15.8 MB 861.4 kB/s eta 0:00:11
   ----------------- ---------------------- 6.9/15.8 MB 863.2 kB/s eta 0:00:11
   ----------------- ---------------------- 7.0/15.8 MB 862.9 kB/s eta 0:00:11
   ----------------- ---------------------- 7.0/15.8 MB 864.6 kB/s eta 0:00:11
   ----------------- ---------------------- 7.1/15.8 MB 863.4 kB/s eta 0:00:11
   ------------------ --------------------- 7.1/15.8 MB 864.8 kB/s eta 0:00:11
   ------------------ --------------------- 7.1/15.8 MB 863.6 kB/s eta 0:00:11
   ------------------ --------------------- 7.2/15.8 MB 862.4 kB/s eta 0:00:10
   ------------------ --------------------- 7.2/15.8 MB 861.2 kB/s eta 0:00:10
   ------------------ --------------------- 7.2/15.8 MB 860.0 kB/s eta 0:00:10
   ------------------ --------------------- 7.3/15.8 MB 861.3 kB/s eta 0:00:10
   ------------------ --------------------- 7.3/15.8 MB 862.6 kB/s eta 0:00:10
   ------------------ --------------------- 7.4/15.8 MB 865.4 kB/s eta 0:00:10
   ------------------ --------------------- 7.5/15.8 MB 866.3 kB/s eta 0:00:10
   ------------------- -------------------- 7.5/15.8 MB 869.9 kB/s eta 0:00:10
   ------------------- -------------------- 7.6/15.8 MB 870.3 kB/s eta 0:00:10
   ------------------- -------------------- 7.6/15.8 MB 871.5 kB/s eta 0:00:10
   ------------------- -------------------- 7.6/15.8 MB 870.4 kB/s eta 0:00:10
   ------------------- -------------------- 7.7/15.8 MB 869.2 kB/s eta 0:00:10
   ------------------- -------------------- 7.7/15.8 MB 869.6 kB/s eta 0:00:10
   ------------------- -------------------- 7.7/15.8 MB 868.5 kB/s eta 0:00:10
   ------------------- -------------------- 7.8/15.8 MB 868.1 kB/s eta 0:00:10
   ------------------- -------------------- 7.8/15.8 MB 868.5 kB/s eta 0:00:10
   ------------------- -------------------- 7.9/15.8 MB 868.1 kB/s eta 0:00:10
   ------------------- -------------------- 7.9/15.8 MB 869.0 kB/s eta 0:00:10
   -------------------- ------------------- 7.9/15.8 MB 868.6 kB/s eta 0:00:10
   -------------------- ------------------- 8.0/15.8 MB 866.4 kB/s eta 0:00:10
   -------------------- ------------------- 8.0/15.8 MB 865.4 kB/s eta 0:00:10
   -------------------- ------------------- 8.0/15.8 MB 865.7 kB/s eta 0:00:09
   -------------------- ------------------- 8.1/15.8 MB 864.3 kB/s eta 0:00:09
   -------------------- ------------------- 8.1/15.8 MB 864.8 kB/s eta 0:00:09
   -------------------- ------------------- 8.1/15.8 MB 863.7 kB/s eta 0:00:09
   -------------------- ------------------- 8.2/15.8 MB 863.4 kB/s eta 0:00:09
   -------------------- ------------------- 8.2/15.8 MB 862.3 kB/s eta 0:00:09
   -------------------- ------------------- 8.2/15.8 MB 862.7 kB/s eta 0:00:09
   -------------------- ------------------- 8.3/15.8 MB 861.7 kB/s eta 0:00:09
   -------------------- ------------------- 8.3/15.8 MB 861.1 kB/s eta 0:00:09
   --------------------- ------------------ 8.3/15.8 MB 860.0 kB/s eta 0:00:09
   --------------------- ------------------ 8.3/15.8 MB 857.7 kB/s eta 0:00:09
   --------------------- ------------------ 8.4/15.8 MB 855.3 kB/s eta 0:00:09
   --------------------- ------------------ 8.4/15.8 MB 856.0 kB/s eta 0:00:09
   --------------------- ------------------ 8.4/15.8 MB 853.8 kB/s eta 0:00:09
   --------------------- ------------------ 8.4/15.8 MB 853.2 kB/s eta 0:00:09
   --------------------- ------------------ 8.5/15.8 MB 850.8 kB/s eta 0:00:09
   --------------------- ------------------ 8.5/15.8 MB 849.9 kB/s eta 0:00:09
   --------------------- ------------------ 8.6/15.8 MB 851.0 kB/s eta 0:00:09
   --------------------- ------------------ 8.6/15.8 MB 851.5 kB/s eta 0:00:09
   --------------------- ------------------ 8.6/15.8 MB 850.3 kB/s eta 0:00:09
   --------------------- ------------------ 8.7/15.8 MB 850.6 kB/s eta 0:00:09
   ---------------------- ----------------- 8.7/15.8 MB 849.8 kB/s eta 0:00:09
   ---------------------- ----------------- 8.7/15.8 MB 849.8 kB/s eta 0:00:09
   ---------------------- ----------------- 8.8/15.8 MB 848.0 kB/s eta 0:00:09
   ---------------------- ----------------- 8.8/15.8 MB 848.1 kB/s eta 0:00:09
   ---------------------- ----------------- 8.8/15.8 MB 848.6 kB/s eta 0:00:09
   ---------------------- ----------------- 8.9/15.8 MB 849.7 kB/s eta 0:00:09
   ---------------------- ----------------- 8.9/15.8 MB 849.4 kB/s eta 0:00:09

In [3]:
import pandas as pd
import numpy as np

In [5]:
# data 폴더에 있는 파일을 읽어 온다.

movie_df = pd.read_json('./data/movie.json')

In [6]:
movie_df

       id                              title
0       1                             Planes
1       2  Big Mommas: Like Father, Like Son
2       3                   Babes in Toyland
3       4             Million Dollar Mystery
4       5                       Street Kings
..    ...                                ...
995   996               Journey for Margaret
996   997                    Black Hole, The
997   998                    Little Fugitive
998   999    Monty Python and the Holy Grail
999  1000           Loins of Punjab Presents

[1000 rows x 2 columns]

In [8]:
review_df = pd.read_json('./data/review.json')

In [11]:
review_df.drop( 'id' , axis = 1, inplace= True)

In [12]:
review_df

      movieId  userId  rating
0           3       1       4
1         863     189       4
2         608     217       3
3         405       6       2
4         959     238       5
...       ...     ...     ...
1002       44     302       4
1003       22     302       1
1004      821     302       5
1005      445     302       1
1006      981     302       4

[1007 rows x 3 columns]

In [15]:
movie_df.rename( columns= {'id' : 'movieId'} , inplace= True )

In [16]:
movie_df.head(2)

   movieId                              title
0        1                             Planes
1        2  Big Mommas: Like Father, Like Son

In [17]:
review_df.head(2)

   movieId  userId  rating
0        3       1       4
1      863     189       4

In [20]:
df = pd.merge(movie_df, review_df, on = 'movieId', how= 'left' )

In [21]:
df

      movieId                              title  userId  rating
0           1                             Planes   286.0     4.0
1           2  Big Mommas: Like Father, Like Son   109.0     2.0
2           2  Big Mommas: Like Father, Like Son   188.0     3.0
3           2  Big Mommas: Like Father, Like Son   243.0     4.0
4           3                   Babes in Toyland     1.0     4.0
...       ...                                ...     ...     ...
1376      997                    Black Hole, The   178.0     3.0
1377      997                    Black Hole, The   205.0     1.0
1378      998                    Little Fugitive   113.0     2.0
1379      999    Monty Python and the Holy Grail   224.0     4.0
1380     1000           Loins of Punjab Presents     NaN     NaN

[1381 rows x 4 columns]

In [23]:
# 각 영화 제목별로, 별점에 대한 기본통계치를 확인해 보자.

df.groupby('movieId')['rating'].describe()

         count      mean       std  min  25%  50%  75%  max
movieId
1          1.0  4.000000       NaN  4.0  4.0  4.0  4.0  4.0
2          3.0  3.000000  1.000000  2.0  2.5  3.0  3.5  4.0
3          3.0  4.000000  1.000000  3.0  3.5  4.0  4.5  5.0
4          1.0  3.000000       NaN  3.0  3.0  3.0  3.0  3.0
5          0.0       NaN       NaN  NaN  NaN  NaN  NaN  NaN
...        ...       ...       ...  ...  ...  ...  ...  ...
996        0.0       NaN       NaN  NaN  NaN  NaN  NaN  NaN
997        3.0  1.666667  1.154701  1.0  1.0  1.0  2.0  3.0
998        1.0  2.000000       NaN  2.0  2.0  2.0  2.0  2.0
999        1.0  4.000000       NaN  4.0  4.0  4.0  4.0  4.0
1000       0.0       NaN       NaN  NaN  NaN  NaN  NaN  NaN

[1000 rows x 8 columns]

In [24]:
df.groupby('title')['rating'].describe()

,count,mean,std,min,25%,50%,75%,max
title,,,,,,,,
"1, 2, 3, Sun (Un, deuz, trois, soleil)",0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112 Weddings,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12 Storeys (Shier lou),3.0,4.333333,1.154701,3.0,4.0,5.0,5.0,5.0
13 Ghosts,1.0,3.000000,NaN,3.0,3.0,3.0,3.0,3.0
2019: After the Fall of New York,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
"Young Black Stallion, The",3.0,4.333333,0.577350,4.0,4.0,4.0,4.5,5.0
Zombie (a.k.a. Zombie 2: The Dead Are Among U,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zombies of the Stratosphere,1.0,3.000000,NaN,3.0,3.0,3.0,3.0,3.0
Zone 39,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zulu Dawn,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df

      movieId                              title  userId  rating
0           1                             Planes   286.0     4.0
1           2  Big Mommas: Like Father, Like Son   109.0     2.0
2           2  Big Mommas: Like Father, Like Son   188.0     3.0
3           2  Big Mommas: Like Father, Like Son   243.0     4.0
4           3                   Babes in Toyland     1.0     4.0
...       ...                                ...     ...     ...
1376      997                    Black Hole, The   178.0     3.0
1377      997                    Black Hole, The   205.0     1.0
1378      998                    Little Fugitive   113.0     2.0
1379      999    Monty Python and the Holy Grail   224.0     4.0
1380     1000           Loins of Punjab Presents     NaN     NaN

[1381 rows x 4 columns]

In [27]:
df.corr(numeric_only= True)

          movieId    userId    rating
movieId  1.000000 -0.028923  0.029548
userId  -0.028923  1.000000 -0.021453
rating   0.029548 -0.021453  1.000000

In [ ]:
# 영화 제목이 모두 컬럼으로 가있어야지, 상관계수를 뽑을 수 있다. 

# 왜왜. corr() 함수는, 컬럼과 컬럼의 관계를 뽑아주니까.

In [30]:
review_df['userId'].nunique()

295

In [31]:
df

      movieId                              title  userId  rating
0           1                             Planes   286.0     4.0
1           2  Big Mommas: Like Father, Like Son   109.0     2.0
2           2  Big Mommas: Like Father, Like Son   188.0     3.0
3           2  Big Mommas: Like Father, Like Son   243.0     4.0
4           3                   Babes in Toyland     1.0     4.0
...       ...                                ...     ...     ...
1376      997                    Black Hole, The   178.0     3.0
1377      997                    Black Hole, The   205.0     1.0
1378      998                    Little Fugitive   113.0     2.0
1379      999    Monty Python and the Holy Grail   224.0     4.0
1380     1000           Loins of Punjab Presents     NaN     NaN

[1381 rows x 4 columns]

In [33]:
df_all = df.pivot_table(index= 'userId', columns= 'title', values='rating', aggfunc='mean')

In [38]:
## 샘플데이터는 리뷰가 많아야 3개정도라서 정확도가 떨어질수밖에 없다.
## 별점의 갯수가 특정 갯수 이하인 것은, 상관분석에서 뺄수 있다. 
## 반대로 말하면, 별점의 갯수가 특정갯수 이상인것만 유의미한 상관계수를 뽑도록
## 할수 있다. 

corr_movie = df_all.corr(min_periods= 2)

In [62]:
corr_movie['13 Ghosts'].dropna()

Series([], Name: 13 Ghosts, dtype: float64)

In [ ]:
# 개인 맞춤형 영화 추천을 해야 하므로, 
# 로그인 한 사람의 리뷰 정보를 기반으로해서 추천을 해줘야 한다.

In [48]:
my_rating = pd.read_json('./data/my_rating.json')

In [49]:
my_rating

                                         title  rating
0                             Babes in Toyland       4
1         Silver Stallion (Silver Brumpy, The)       4
2                             There Be Dragons       3
3                                Hireling, The       3
4  I Have Found It (Kandukondain Kandukondain)       3

In [53]:
title = my_rating['title'][0]

In [54]:
title

'Babes in Toyland'

In [57]:
corr_movie[title].dropna()

title
Babes in Toyland    1.0
Name: Babes in Toyland, dtype: float64

In [63]:
movie_df = pd.read_csv('./data/Movie_Id_Titles.csv')

In [64]:
review_df = pd.read_csv('./data/user_rating.csv')

In [68]:
df = pd.merge(movie_df, review_df, on='item_id', how='left')

In [71]:
df_all = df.pivot_table(index= 'user_id', columns='title', values='rating', aggfunc='mean')

In [75]:
corr_movie = df_all.corr(min_periods= 50 )

In [76]:
corr_movie

title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
title,,,,,,,,,,,,,,,,,,,,,
'Til There Was You (1997),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1-900 (1994),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101 Dalmatians (1996),NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12 Angry Men (1957),NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.178848,NaN,NaN,...,NaN,NaN,NaN,0.096546,NaN,NaN,NaN,NaN,NaN,NaN
187 (1997),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Young Guns II (1990),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Young Poisoner's Handbook, The (1995)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zeus and Roxanne (1997),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Á köldum klaka (Cold Fever) (1994),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
my_rating = pd.read_csv('./data/My_Ratings.csv')

In [78]:
my_rating

                     Movie Name  Ratings
0         101 Dalmatians (1996)        5
1  2001: A Space Odyssey (1968)        4
2           You So Crazy (1994)        1

In [81]:
title = my_rating['Movie Name'][0]

In [82]:
title

'101 Dalmatians (1996)'

In [87]:
recom_movie = corr_movie[title].dropna().sort_values(ascending=False).to_frame()

In [90]:
recom_movie.columns = ['corr']

In [93]:
recom_movie['weight'] = recom_movie['corr'] * my_rating['Ratings'][0]

In [94]:
recom_movie

                                         corr    weight
title
101 Dalmatians (1996)                1.000000  5.000000
Top Gun (1986)                       0.492492  2.462461
Hunt for Red October, The (1990)     0.483807  2.419033
Liar Liar (1997)                     0.469765  2.348824
Grumpier Old Men (1995)              0.461647  2.308235
...                                       ...       ...
Star Trek: The Wrath of Khan (1982) -0.115497 -0.577487
Groundhog Day (1993)                -0.126499 -0.632497
Twelve Monkeys (1995)               -0.184141 -0.920703
Alien (1979)                        -0.190265 -0.951326
Fargo (1996)                        -0.245368 -1.226842

[76 rows x 2 columns]

In [96]:
# 비어있는 데이터프레임 만들고, 
# 내가 본 영화의 가중치까지 계산해서, 추천영화를 뽑아내자.
# 추천영화들을 비어있는 데이터프레임에 추가하면 된다.

In [98]:
movie_list = pd.DataFrame()

for i in range( my_rating.shape[0] ) :
    title = my_rating['Movie Name'][i]
    recom_movie = corr_movie[title].dropna().sort_values(ascending=False).to_frame()
    recom_movie.columns = ['corr']
    recom_movie['weight'] = recom_movie['corr'] * my_rating['Ratings'][i]
    movie_list = pd.concat( [movie_list, recom_movie] )

In [101]:
movie_list.sort_values('weight', ascending=False, inplace=True)

In [102]:
movie_list

                                         corr    weight
title
101 Dalmatians (1996)                1.000000  5.000000
2001: A Space Odyssey (1968)         1.000000  4.000000
Top Gun (1986)                       0.492492  2.462461
Hunt for Red October, The (1990)     0.483807  2.419033
Liar Liar (1997)                     0.469765  2.348824
...                                       ...       ...
Sword in the Stone, The (1963)      -0.238260 -0.953042
Jungle Book, The (1994)             -0.264809 -1.059235
So I Married an Axe Murderer (1993) -0.276184 -1.104736
Air Force One (1997)                -0.282994 -1.131976
Fargo (1996)                        -0.245368 -1.226842

[434 rows x 2 columns]

In [104]:
# 내가 이미 본 영화는 추천에서 제외한다. 
for title in my_rating['Movie Name'] :
    if title in movie_list.index :
        movie_list.drop(title, axis = 0, inplace=True)

In [106]:
# 이 리스트에는, 중복된 영화도 있을 수 있다. 
# 따라서 중복된 영화가 있으면, 웨이트점수가 높은것으로만 
# 나오도록 한다.

In [112]:
movie_list.groupby('title')['weight'].max().sort_values(ascending=False)

title
Top Gun (1986)                         2.462461
Hunt for Red October, The (1990)       2.419033
Liar Liar (1997)                       2.348824
Grumpier Old Men (1995)                2.308235
Lion King, The (1994)                  2.132864
                                         ...
Army of Darkness (1993)               -0.898622
Sword in the Stone, The (1963)        -0.953042
Jungle Book, The (1994)               -1.059235
So I Married an Axe Murderer (1993)   -1.104736
Air Force One (1997)                  -1.131976
Name: weight, Length: 358, dtype: float64

In [113]:
corr_movie.to_csv('corr_movie.csv')

title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
title,,,,,,,,,,,,,,,,,,,,,
'Til There Was You (1997),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1-900 (1994),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101 Dalmatians (1996),NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12 Angry Men (1957),NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.178848,NaN,NaN,...,NaN,NaN,NaN,0.096546,NaN,NaN,NaN,NaN,NaN,NaN
187 (1997),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Young Guns II (1990),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Young Poisoner's Handbook, The (1995)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zeus and Roxanne (1997),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Á köldum klaka (Cold Fever) (1994),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN